routes/web.php
<?php

use Illuminate\Support\Facades\Route;




require __DIR__.'/admin_routes.php';

require __DIR__.'/frontend_routes.php';

Route::get('/clear', function() {
	Artisan::call('cache:clear');
	Artisan::call('view:clear');
	Artisan::call('config:clear');
	//Artisan::call('route:clear');
	return "Cache is cleared";
});



Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'admin']], function () {
	\UniSharp\LaravelFilemanager\Lfm::routes();
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

use Illuminate\Database\Eloquent\SoftDeletes;
use LamaLama\Wishlist\HasWishlists;


class User extends Authenticatable
{
  use SoftDeletes;
  use HasWishlists;

  protected $table = 'users';

  protected $fillable = ['name','sname', 'email', 'pass', 'activation_key', 'is_active', 'is_admin' ];

  protected $hidden = ['pass', 'activation_key'];



  function getAuthPassword()
  {
    return $this->pass;
  }

  public function getDetail()
  {
    return $this->hasOne('App\Models\UserDetail')->withDefault();
  }

  public function getAdres()
  {
    return $this->hasOne('App\Models\UserAdres')->withDefault();
  }

  public function getFullNameAttribute()
  {
   return ucwords_tr($this->name) . ' ' . ucwords_tr($this->sname);
 }

}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

use App\Models\User;
use App\Models\UserDetail;
use Auth;

class UserController extends Controller
{
	function login()
	{
		if (request()->isMethod('POST')) {
			$this->validate(request(), [
				'email' => 'required|email',
				'password' => 'required'
			]);

			$credentials = [
				'email' => request()->get('email'),
				'password' => request()->get('password'),
				'is_admin' => 1,
				'is_active' => 1
			];

			if (Auth::guard('yonetim')->attempt($credentials, request()->has('remember'))) {
				return redirect()->route('crudv4.home');
			}
			else{
				return back()->withInput()->withErrors(['email' => 'Giriş htalı!']);
			}
		}
		return view('admin.login');
	}

	function logout()
	{
		Auth::guard('yonetim')->logout();
		request()->session()->flush(); //session sıfırla
		request()->session()->regenerate(); //session yeniden oluştur
		return redirect()->route('crudv4.login'); //anasayfaya git
	}

	function index()
	{
		$list = User::where('is_admin',1)->orderby('created_at','asc')->get();

		$title ="Yöneticiler";

		return view('admin.user.index',compact('list','title'));
	}

	function member()
	{
		$list = User::where('is_admin',0)->orderby('created_at','asc')->get();

		$title ="Site Üyeleri";

		return view('admin.user.index',compact('list','title'));
	}


	function form($id=0)
	{
		$entry = new User;
		if ($id>0) {
			$entry = User::find($id);
		}

		$title ="Kullanıcı Düzenleme Formu";

		return view('admin.user.form',compact('entry','title',"id"));
	}

	function save($id=0)
	{
		$this->validate(request(),[
			'name' => 'required',
			'sname' => 'required',
			'email' => 'required|email'
		]);

		$data = request()->only('name','sname','email');

		if (request()->filled('pass')) {
			$data['pass'] = Hash::make(request('pass'));
		}

		$data['is_active'] = request()->has('is_active') && request('is_active')==1 ? 1 : 0;

		$data['is_admin'] = request()->has('is_admin') && request('is_admin')==1 ? 1 : 0;
		/*
		if(request()->has('aktif_mi'))
			$data['aktif_mi'] = 1;
		else
		$data['aktif_mi'] = 0; */


		if ($id>0) {
			$entry = User::where('id',$id)->firstOrFail();
			$entry->update($data);
			$page = "edit";

		}else{
			$entry = User::create($data);
			$page = "add";
		}

		UserDetail::updateOrCreate(
			['user_id' => $entry->id],
			[
				'user_address' => request('user_address'),
				'user_tel' => request('user_tel'),
				'user_gsm' => request('user_gsm')
			]
		);

		return redirect()
		->route('crudv4.user.'.$page,$entry->id)
		->with('mesaj',($id>0 ? 'Kullanici Güncellendi' : 'Kullanici Kaydedildi'))
		->with('mesaj_tur','success');
	}

	function del($id)
	{
		$user = User::find($id);
		//$user->getDetail()->delete();
		$user->delete();

		return "1";
	}
}

resources/views/admin/user/form.blade.php
@extends('admin.layouts.master')
@section('title', $title)
@section('body')

<form action="{{ route('crudv4.user.save', @$entry->id) }}" class="container-fluid row" id="userForm" method="POST" enctype="multipart/form-data">
	{{csrf_field()}}

	@include('admin.layouts.errors')
	@include('admin.layouts.alert')


	<div class="col-sm-12 col-lg-8">

		<div class="iq-card">
			<div class="iq-card-header d-flex justify-content-between">
				<div class="iq-header-title col-md-6">
					<h4 class="card-title">{{ $title }} </h4>
				</div>
				<div class="col-md-6">
					<a href="{{ route('crudv4.user') }}" class="btn btn-primary float-right"> <i class="fa fa-angle-left"></i> Geri</a>
				</div>
			</div>
			<div class="iq-card-body">


				<div class="row">

					<div class="form-group col-6">
						<label  >İsim:</label>
						<div class="input-group">
							<div class="input-group-prepend">
								<span class="input-group-text  bg-primary"  ><i class="fa fa-user"></i></span>
							</div>
							<input type="text" class="form-control req" name="name" value="{{ $entry->name }}">
						</div>
					</div>

					<div class="form-group col-6">
						<label  >Soy İsim:</label>
						<div class="input-group">
							<div class="input-group-prepend">
								<span class="input-group-text  bg-success"  ><i class="fa fa-user-o"></i></span>
							</div>
							<input type="text" class="form-control req" name="sname" value="{{ $entry->sname }}">
						</div>
					</div>

				</div>
				<div class="row">
					<div class="form-group col-6">
						<label  >E-Posta:</label>
						<div class="input-group">
							<div class="input-group-prepend">
								<span class="input-group-text  bg-info"  ><i class="fa fa-envelope"></i></span>
							</div>
							<input type="text" class="form-control req" name="email" value="{{ $entry->email }}">
						</div>
					</div>

					<div class="form-group col-6">
						<label  >Şifre:</label>
						<div class="input-group">
							<div class="input-group-prepend">
								<span class="input-group-text  bg-primary"  ><i class="fa fa-key"></i></span>
							</div>
							<input type="text" class="form-control" name="pass" value="">

						</div>
						<small class="text-muted">Güncellemek istemiyorsanız boş bırakın</small>
					</div>
				</div>

				@if ($id>0)

				<div class="row">
					<div class="col-sm-6 pt10">
						<label  >Durum:</label>
						<div class="custom-control custom-radio custom-radio-color-checked custom-control-inline">
							<input type="radio" id="is_active1" name="is_active" value="1" class="custom-control-input bg-primary" {{ $entry->is_active==1?"checked":"" }}>
							<label class="custom-control-label" for="is_active1"> Aktif </label>
						</div>
						<div class="custom-control custom-radio custom-radio-color-checked custom-control-inline">
							<input type="radio" id="is_active2" value="0" name="is_active" class="custom-control-input bg-danger" {{ $entry->is_active==0?"checked":"" }}>
							<label class="custom-control-label" for="is_active2"> Pasif </label>
						</div>
					</div>

					<div class="col-sm-6 pt10">
						<label  >Rol:</label>
						<div class="custom-control custom-radio custom-radio-color-checked custom-control-inline">
							<input type="radio" id="is_admin1" name="is_admin" value="1" class="custom-control-input bg-primary" {{ $entry->is_admin==1?"checked":"" }}>
							<label class="custom-control-label" for="is_admin1"> Yönetici </label>
						</div>
						<div class="custom-control custom-radio custom-radio-color-checked custom-control-inline">
							<input type="radio" id="is_admin2" value="0" name="is_admin" class="custom-control-input bg-danger" {{ $entry->is_admin==0?"checked":"" }}>
							<label class="custom-control-label" for="is_admin2"> Kullanıcı </label>
						</div>
					</div>
				</div>

				@else
				<div class="row">
					<div class="col-sm-6 pt10">
						<label  >Durum:</label>
						<div class="custom-control custom-radio custom-radio-color-checked custom-control-inline">
							<input type="radio" id="is_active1" name="is_active" value="1" class="custom-control-input bg-primary" checked>
							<label class="custom-control-label" for="is_active1"> Aktif </label>
						</div>
						<div class="custom-control custom-radio custom-radio-color-checked custom-control-inline">
							<input type="radio" id="is_active2" value="0" name="is_active" class="custom-control-input bg-danger"  >
							<label class="custom-control-label" for="is_active2"> Pasif </label>
						</div>
					</div>

					<div class="col-sm-6 pt10">
						<label  >Rol:</label>
						<div class="custom-control custom-radio custom-radio-color-checked custom-control-inline">
							<input type="radio" id="is_admin1" name="is_admin" value="1" class="custom-control-input bg-primary"  >
							<label class="custom-control-label" for="is_admin1"> Yönetici </label>
						</div>
						<div class="custom-control custom-radio custom-radio-color-checked custom-control-inline">
							<input type="radio" id="is_admin2" value="0" name="is_admin" class="custom-control-input bg-danger" checked>
							<label class="custom-control-label" for="is_admin2"> Kullanıcı </label>
						</div>
					</div>
				</div>
				@endif



				<div class="row">
					<div class="form-group col-6">
						<label  >GSM:</label>
						<div class="input-group">
							<div class="input-group-prepend">
								<span class="input-group-text  bg-success"  ><i class="fa fa-phone"></i></span>
							</div>
							<input type="text" class="form-control" name="user_gsm" value="{{ $entry->getDetail->user_gsm }}">
						</div>
					</div>

					<div class="form-group col-6">
						<label  >Alternatif Tel:</label>
						<div class="input-group">
							<div class="input-group-prepend">
								<span class="input-group-text  bg-secondary"  ><i class="fa fa-phone"></i></span>
							</div>
							<input type="text" class="form-control" name="user_tel"   value="{{ $entry->getDetail->user_tel }}">

						</div>
						<small class="text-muted">Güncellemek istemiyorsanız boş bırakın</small>
					</div>
				</div>


				<div class="form-group">
					<label >Kullanıcı Adres <small>(Zorunlu Değil)</small></label>
					<textarea class="form-control lh23"   name="user_address">{{ $entry->getDetail->user_address }}</textarea>
					<p class="form-text"></p>
				</div>





			</div>
		</div>
		<button type="button" data-id="userForm" class="btn btn-block btn-primary sbmt_btn">{{ $id>0?"Güncelle":"Ekle" }}</button>
	</div>	



</form>


@endsection


@section('script')


@endsection

resources/views/admin/user/index.blade.php
@extends('admin.layouts.master')
@section('title', $title)
@section('body')



<div class="col-sm-12">
	<div class="iq-card">
		<div class="iq-card-header d-flex justify-content-between">
			<div class="iq-header-title col-md-6">

				<h4 class="card-title">{{ $title }} </h4>
			</div>
			<div class="col-md-6">
				<a href="{{ route('crudv4.user.add') }}" class="btn btn-primary float-right btn-lg" ><i class="fa fa-plus"></i> Yeni Ekle</a>
			</div>
		</div>
		<div class="iq-card-body">

			<table class="table">
				<thead>
					<tr>
						<th scope="col">#</th>
						<th scope="col">Ad Soyad</th>
						<th scope="col">E-Posta</th>
						<th scope="col">İşlem</th>
					</tr>
				</thead>
				<tbody>
					@foreach($list as $row)
					
					<tr id="tr_{{ $row->id }}">
						<td scope="row">{{$loop->iteration}}</td>
						<td>{{ $row->full_name }}</td>
						<td>{{ $row->email }}</td>
						<td>


							<div class="flex align-items-center list-user-action">

								<a class="iq-bg-primary tipsi" title="Düzenle" href="{{ route('crudv4.user.edit',$row->id) }}" ><i class="ri-pencil-line"></i></a>
								<a  class="iq-bg-primary tipsi" title="Sil"  onclick="allConfirm('eraseci',{{ $row->id }})" href="javascript:;"><i class="ri-delete-bin-line"></i></a>

							</div>


						</td>
					</tr>
					@endforeach


				</tbody>
			</table>
		</div>
	</div>
</div>



@endsection


@section('script')
<script>

	function eraseci(id) {

		$.ajax({
			type: 'GET',
			url: '/crudv4/user/del/' + id,
			success: function () {
				sole('İşlem Başarılı',"Silme işlemi Başarıyla Gerçekleştirildi.")
				$('#tr_'+id).remove()
			} 

		});
	}

	
</script>
@endsection